# version: "3.8"

services:
  web:
    image: odoo:19
    restart: always
    ports:
      - "8070:8069"
    depends_on:
      - db
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./custom_addons:/mnt/extra-addons

  db:
    image: postgres:15
    restart: always
    ports:
      - "5433:5432" # Opens PostgreSQL to the outside world
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - odoo-db-data:/var/lib/postgresql/data
    command: |
      postgres -c listen_addresses='*'

volumes:
  odoo-web-data:
  odoo-db-data:
